# Generated by Django 5.0.2 on 2024-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(verbose_name='date uploaded')),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
